# Generated by Django 2.2.1 on 2019-05-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
