# Generated by Django 2.2.1 on 2019-07-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapy', '0005_auto_20190731_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
