# Generated by Django 2.2.1 on 2019-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapy', '0006_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
    ]
