# Generated by Django 2.2.1 on 2019-07-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapy', '0007_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
